# Generated by Django 2.2.2 on 2019-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_something'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='connection',
            field=models.BooleanField(default=False),
        ),
    ]
