# Generated by Django 2.2.2 on 2019-06-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='something',
        ),
    ]
