version: '3'

services:
  database:
    container_name: portfolio_db
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    container_name: rate_my_realtor
    command: python3 manage.py runserver 0.0.0.0:8000
    environment: 
      - "PYTHONUNBUFFERED=1"
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  postgres_data: