# Generated by Django 2.2.2 on 2019-06-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=650)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RealtorAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True)),
                ('phone_number', models.CharField(default=0, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default=None, max_length=250)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.Agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.RealtorAgency'),
        ),
    ]
