# Generated by Django 2.2.2 on 2019-06-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_agentsdata_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsdata',
            name='comments',
            field=models.TextField(default=None, max_length=250),
        ),
    ]
