# Generated by Django 2.2.2 on 2019-06-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_auto_20190615_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='about',
            field=models.CharField(default='No Information', max_length=350),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.Agent')),
            ],
        ),
    ]
