# Generated by Django 2.2.2 on 2019-06-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_auto_20190616_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='about',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='statistics',
        ),
    ]
