# Generated by Django 2.2.2 on 2019-06-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0006_auto_20190616_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='statistics',
        ),
    ]
