# Generated by Django 2.2.2 on 2019-06-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0008_agentsdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='rate',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='agentsdata',
            old_name='rate',
            new_name='rating',
        ),
    ]
