# Generated by Django 2.2.2 on 2019-07-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0008_auto_20190621_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsdata',
            name='rating',
        ),
    ]
