# Generated by Django 2.2.2 on 2019-07-24 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0009_remove_agentsdata_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsdata',
            name='rating',
            field=models.FloatField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
