# Generated by Django 2.2.2 on 2019-06-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0010_agent_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='something',
        ),
        migrations.AlterField(
            model_name='agent',
            name='about',
            field=models.TextField(default='No Information', max_length=350),
        ),
    ]
