# Generated by Django 2.2.2 on 2019-06-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0012_auto_20190618_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='about',
            field=models.TextField(max_length=650),
        ),
    ]
